language: ruby
rvm:
- 2.2
script: "bundle exec jekyll build"

language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i gatsby@2.2.9 -g"
  - "npm ci"
script:
  - "npm run deploy"